## Tensor

One of the most important concept for pytorch is "Tensor"
You can simply consider it as "arrays", but more focusing on multi-dimension presentation.

In [2]:
# In this file, we will get started with pytorch

import torch

# create a tensor with 5 elements, in 1 dimension
x = torch.empty(5)
print(x)

# create a tensor with multi-dimension tensor
x = torch.empty(4,4)
print(x)

# random number normally used to initialize the tensor for initial weights
x = torch.rand(4,4, dtype=torch.float64)
print(x)

# create a tensor from targetted data
x = torch.tensor([5.5, 3])
print(x)



tensor([0., 0., 0., 0., 0.])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0.0290, 0.6128, 0.3270, 0.0847],
        [0.3923, 0.8633, 0.8877, 0.4445],
        [0.1759, 0.7887, 0.4738, 0.1944],
        [0.7167, 0.7652, 0.4049, 0.4006]], dtype=torch.float64)
tensor([5.5000, 3.0000])


In [9]:
# tensor could used like a matrix
x = torch.tensor([1,2,3])
y = torch.tensor([1,2,3])

res = x.add(y)
res = torch.add(x, y)
print(x + y)

print(x * y)
print(x / y)

# if we want to do matrix multiplication, we need to make sure the dimension is correct
print(x @ y.T)
print(x.matmul(y.T))



tensor([2, 4, 6])
tensor([1, 4, 9])
tensor([1., 1., 1.])
tensor(14)
tensor(14)


In [15]:
# we could also process normal array operation to the tensor

x = torch.rand(4,4)
print(x[:,0])
print(x[2,2].item())

tensor([0.2098, 0.4942, 0.1114, 0.7673])
0.7412450909614563


In [21]:
# to cast a tensor to a different shape, we could use view, note we need give proper size where a*b*c... will still remains the same size

x = torch.rand(4,4)
print(x, x.size())

x = x.view(-1)
print(x, x.size())

# we could also convert the tensor to numpy array
x = torch.rand(4,4)
print(x)





tensor([[0.0228, 0.3914, 0.1785, 0.5791],
        [0.8497, 0.2389, 0.1361, 0.4238],
        [0.8639, 0.7143, 0.2610, 0.2415],
        [0.6532, 0.2462, 0.6692, 0.3121]]) torch.Size([4, 4])
tensor([0.0228, 0.3914, 0.1785, 0.5791, 0.8497, 0.2389, 0.1361, 0.4238, 0.8639,
        0.7143, 0.2610, 0.2415, 0.6532, 0.2462, 0.6692, 0.3121]) torch.Size([16])
tensor([[0.5397, 0.8333, 0.0593, 0.7762],
        [0.0049, 0.2483, 0.2726, 0.1005],
        [0.7650, 0.1428, 0.7130, 0.7097],
        [0.9834, 0.9542, 0.3014, 0.2690]])


In [26]:
# here is an example how we can cast numpy array to tensor and vice versa
import numpy as np

a = np.ones(5, dtype=np.float32)
b = torch.from_numpy(a)

# if we change the numpy array, the tensor will also change
a += 1
print(a)
print(b)
print(b.numpy())

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


# The last thing here is we need to target our computing resource
If we dont define anything, it will fall into CPU bucket, which is pretty slow to compute

In [31]:
device = torch.device("cpu")
if torch.cuda.is_available():
    device = torch.device("cuda")
elif torch.backends.mps.is_available():
    device = torch.device("mps")

print(device)

# the following code will return an error since they are run in different device
x = torch.rand(4,4)
y = torch.rand(4,4)

x = x.to(device)
z = y + x
z.to(device, torch.double)
print(z)




mps


RuntimeError: Expected all tensors to be on the same device, but found at least two devices, mps:0 and cpu!

In [ ]:
# bounus, we need to tell the pytorch to track the gradient

x = torch.ones(5, requires_grad=True)


